### ISSUE TITLE
Script to update/select another version of Wine

### ISSUE THREAD

**Issue by inaciopestana** [phoenixbyrd/Termux_XFCE#52]
Hi,

I wonder if you can provide a script to update/change/select another version of Wine that is installed by defaut.
I spent all day tring to change your script to make it work, but Wine wont load if I just replace the version from your script to the current one.

If you can't provide the script, please, can you point me directions to do that? Appreciate your work, thanks.

**Comment by rashidtvmr** [comment]
Yes please provide script if possible

**Comment by phoenixbyrd** [comment]
All scripts for everything are available in my github pages. App Installer has its own page. I haven't had time to do much due to work and life. Wine has been an issue for me too, honestly thinking of removing it since it doesn't work anywhere nearly as good as other alternatives for running windows stuff in termux.
