### ISSUE TITLE
Termux_XFCE VNC?

### ISSUE THREAD

**Issue by Zo0m4ek** [phoenixbyrd/Termux_XFCE#65]
I decided to make a kind of Raspberry Pi from my phone, usually for this purpose used the script “tmoe” in conjunction with “noVNC” or “x11vnc”, but due to the irrelevance of this script with its distributions, decided to try this one. Is there any possibility to use VNC?

**Comment by phoenixbyrd** [comment]
I don't use vnc, I use termux:x11 ... idk much about vnc so I'd google it and see if you can get that working. I tried in the beginning and decided against it due to how crap the performance was compared to native termux:x11. I personally have zero plans on supporting it. I wish you luck and success though.
